a= int(input("enter any number1"))
b= int(input("enter any number2"))
#by int we means the integer otherise it is a string
print("addition is", a+b)
print("subtraction is", a-b)
print("multiplicatiin is", a*b)
print("division is", a/b)
print("exponentiaion is", a**b)
print("floor division is", a//b)
print("modulus", a%b)